- name: nginx
  hosts: web_server
  become: true
  tags:
  - nginx

  tasks:

  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Change main page
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.nginx-debian.html
      owner: root
      group: root
      mode: 0644

- name: filebeat
  hosts: web_server
  become: true
  tags:
  - filebeat

  tasks:


  - name: Install filebeat
    ansible.builtin.apt:
      deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.14-amd64.deb

  - name: Change config file
    ansible.builtin.template:
      src: template/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: 0600

  - name: Make sure a service unit is running
    ansible.builtin.service:
      name: filebeat
      state: started
      enabled: yes


- name: elasticsearch
  hosts: elasticsearch_server
  become: true
  tags:
  - elastic

  tasks:

  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes

  - name: Install elasticsearch
    ansible.builtin.apt:
      deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.14-amd64.deb

  - name: Change config file
    ansible.builtin.template:
      src: template/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: elasticsearch
      mode: 0660

  - name: Make sure a service unit is running
    ansible.builtin.service:
      name: elasticsearch
      state: started
      enabled: yes

- name: kibana
  hosts: kibana_server
  become: true
  tags:
  - kibana

  tasks:

  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes

  - name: Install kibana
    ansible.builtin.apt:
      deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.14-amd64.deb

  - name: Change config file
    ansible.builtin.template:
      src: template/kibana.yml
      dest: /etc/kibana/kibana.yml
      owner: root
      group: kibana
      mode: 0660

  - name: Make sure a service unit is running
    ansible.builtin.service:
      name: kibana
      state: started
      enabled: yes
