---
# tasks file for zabbix_server

- name: "Install Zabbix deb package from the internet"
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
    update_cache: yes

- name: "Install zabbix-server and other pkg"
  ansible.builtin.apt:
    pkg:
      - zabbix-server-pgsql
      - postgresql-client
      - python3-pip
      - zabbix-sql-scripts
    state: latest
    update_cache: yes

- name: "Install pkg for using community.postgresql "
  ansible.builtin.pip:
    name: psycopg2-binary

- name: "Ping PostgreSQL server"
  community.postgresql.postgresql_ping:
    db: "{{ zabbix_server_dbname  }}"
    login_host: "{{ zabbix_server_dbhost }}"
    login_user: "{{ zabbix_server_dbuser  }}"
    login_password: "{{ zabbix_server_dbpassword  }}"
    port: "{{ zabbix_server_dbport  }}"
  register: result

- debug:
        var: result

- name: "Restore database using the tar format"
  community.postgresql.postgresql_db:
    name: zabbix_db
    state: restore
    target: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
    login_host: "{{ zabbix_server_dbhost }}"
    login_user: "{{ zabbix_server_dbuser  }}"
    login_password: "{{ zabbix_server_dbpassword  }}"
    port: "{{ zabbix_server_dbport  }}"

- name: "Copy file with zabbix-server config"
  ansible.builtin.template:
    src: ./zabbix/zabbix_server/templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: '0600'
  become: true
  notify: Restart zabbix-server

- name: "Start zabbix-server if not started"
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: yes
